# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bb638b60840cb7b98c9f1169b20e2f0bf201c7cdfbc71f3720ab5ed6718ff57c3dc728721522f716489ed8419423978b6605484036cb50ae7a478083c7e1945

test:
  secret_key_base: 1a750ee1c47c753add0dda41ba0ea1fd4d9863bd88d524e5cc4eabc73c4a2c1110fe0f59874467a2ad28516bdd2002ccfbe42a0c77aee71eba9b7c791c2a9ce1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
